language: go

go: '1.11'

env:
  global:
  - FILE_TO_DEPLOY="dist/*"
  - GO111MODULE=on

  # GITHUB_TOKEN
  - secure: "MhmvXAAzOA5HY7koCfagX1wJi2mBVQsVF5cCMaNx73l+7uDgNzGYfTn4OGKmckduiGB/mp5bTJ1DeMbPq+TDX1n/RE6kndu/Q/1vw4pbxm9BsmO9b3DizIFoWlnG+EABdAZa9igbCAfv+Jj57a0WjKGaiLazylj1mb7AYj6Vao+1zvm2ufoZvpKJcnKPqcWTsx/enJD3wx0LbqTpN5a/EdynJF9kj9Z97cGk9lS/hQHqmYVUYLYG5ZIvPjkuc6ho6pYaerupZ8aQgwraupRrNAzh70C3QgxnrCK+6RRmBMchhBsHOZq1MGhbN48ttlSMKow2NyVp8mK8+wLUnQgxEvYjVNJBXf5iKMmCTBiTO8IqgAKkkMgLaB3H0UpkeOoUQNTACPxR42+FJcwObmxYRSekTGFPwAAwnZV/1BuPrpxpT7JHa9ELlShz2OVEDz9aK/WC28/oEmtYKN8s9koKr1sx4OT5c0F/XG+er2idgCWwvfK5A0Om7Fudur+bbp1a38QWb00cAu8dPTIONe01vGXQ04d+NyohS2bcvK3iehVpa+WZ4CHkjRRuv6vQGvFMNCtwwQjXopBM99+yAykLm7yqOewbzbxFI7nCHNBc1zHvI13j7yniEoI/vdWk43e2H3Az0OOtdVASNmmp5Avwo/UWzjVACvlyNK1CST4pqYQ="
  # REVIEWDOG_GITHUB_API_TOKEN
  - secure: "HIpuAXhIivyVkMKnWucjuFWJcDnGsvBPm4lQmpCnDOWFFWgblhBzojqN9q0DK91Sc7MEeZPDD3yhZAUOYK2mcRthLZYhbblCjZsE742i8dVB9Y8+PiMb/CHRdERCQUNvQKo+fiXJ4QWE42zx9ehTkKRQHGZkHx8cQVgtSnTyMD2lxxBJWRHUQ8OS+v0yKZCmERisClccbcm37vBQQe3/n6RhuhzxIBlA5G5MEt2ig3noocMcRjApl4Qz3eV/IqVrNs8iQeSm87N3eVxuqMS07SxpOBDhyq6tlU0Ab3VD6peY8aiQxqKLCNU5w0yL5ap9jLiHAV4TDYblS7wUAJLabp+Qdj4/5C2di+jfyn1ZITcKJu8H4kAr8hZqQXpAIQ9K6e/SUztyTfVlsPl9BBO56mx4FB2ZN2voAiJSE4ZUzXyp+zIPk2eiWfclPKiPyvPgFDF0RPV0n/EQXybGoJaLgEnZ4Tx7n2WTWCnZROZkw8EuldIY60D0qJiYYTDfhk2W3XBZUJ4isqrTYKdAP/SGcBLPRmWA2/Aaq7XaP6oHa9+jPIkmhyIALtarWESRbwzWtstXXBjPaUSStZx/J/lvJW2gpmbt8e74GKEEOv9FiX2NOglwN5vPwl7ZErPMdlEeMjOx+HOIts4BPfYwtGFD7Ws0WI4oiSf4PXmuvvzjf4s="

cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build

jobs:
  include:
  - name: lint
    install: make setup
    script: make lint
    if: type = 'pull_request'

  - &test
    install: make setup
    script: make test
    if: type != 'pull_request'

  - &test-e2e
    name: "E2E test (mod)"
    language: bash
    sudo: required
    services:
    - docker
    env:
    - GO_VERSION=1.11.2
    script: make test-e2e
    if: type != 'pull_request'

  - <<: *test
    name: "coverage (go 1.11)"
    script: make cover
    after_success: bash <(curl -s https://codecov.io/bash)

  - <<: *test
    go: master

  # TODO: Skip this because --HEAD option does not work with --use-dep option
  # - <<: *test-e2e
  #   name: "E2E test (dep)"
  #   env:
  #   - GO_VERSION=1.11.2
  #   - USE_DEP=1

  - stage: deploy
    install: make setup
    script: make packages -j4
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: $FILE_TO_DEPLOY
      on:
        tags: true
    if: type != 'pull_request'
