required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
]

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = ""

